[package]
name = "packet"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
pcap-parser = { version = "0.16.0", features = ["data", "serialize"] }
thiserror = "1.0.64"
nom = "7.1.3"
chrono = "0.4.38"
chrono-tz = "0.10.0"